### PR TITLE
Enable Azure Pipelines integration

### PR DESCRIPTION
**Pull request by mrakitin**
Uses https://github.com/NSLS-II/profile-collection-ci.

Currently fails on caproto client (https://dev.azure.com/nsls2/profile_collections/_build/results?buildId=63):
```py
CaprotoTimeoutError‌: &lt;PV name=&#x27;XF:02ID1-ES{RIXSCam}:HDF1:PluginType_RBV&#x27; priority=0 (searching....)&gt; could not connect within 1.0-second timeout.‌
Exception in thread retry:
Traceback (most recent call last):
  File "/home/vsts/mc/envs/collection-2019C3.0.1/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/vsts/mc/envs/collection-2019C3.0.1/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/vsts/mc/envs/collection-2019C3.0.1/lib/python3.6/site-packages/caproto/threading/client.py", line 858, in _retry_unanswered_searches
    SEARCH_MAX_DATAGRAM_BYTES - len(version_req)):
  File "/home/vsts/mc/envs/collection-2019C3.0.1/lib/python3.6/site-packages/caproto/_utils.py", line 772, in batch_requests
    for command in request_iter:
  File "/home/vsts/mc/envs/collection-2019C3.0.1/lib/python3.6/site-packages/caproto/threading/client.py", line 830, in _construct_search_requests
    ca.DEFAULT_PROTOCOL_VERSION)
  File "/home/vsts/mc/envs/collection-2019C3.0.1/lib/python3.6/site-packages/caproto/_commands.py", line 607, in __init__
    ''.format(MAX_RECORD_LENGTH, name, _len))
caproto._utils.CaprotoValueError: EPICS 3.14 imposes a 59-character limit on record names. The record 'XF:02ID1-ES{RIXSCam}:XIP1:HR_ISOLINEAR_CALIBRATION_THRESHOLD' is 60 characters.
```

xref https://github.com/NSLS-II/profile-collection-ci/issues/2

### CODE REVIEW

**Comment by mrakitin** [comment]
attn @danielballan, I encountered another issue with SIX's profile files.

**Comment by mrakitin** [comment]
The problem should be resolved at the IOC level, reported via https://controlsweb.nsls2.bnl.gov/trac/ticket/3906#ticket.

**Comment by mrakitin** [comment]
For now this PR has nothing to do with the IOC configuration, and can be merged to enable the CI integration.

@danielballan, do you mind to have a look?

**Comment by mrakitin** [comment]
The issue #22 will handle the too-long-PV. This PR is good to go.

**Comment by johnsinsheimer** [comment]
Interestingly, I can caget this PV, despite the excessive characters, but I'll see if there is anything I can do with the IOC

**Comment by mrakitin** [comment]
Thank you, @johnsinsheimer! Epics CLI tools (`caget`, ...) and pyepics seem to be quite forgiving, so we haven't noticed the issue until now using caproto.

**Comment by mrakitin** [comment]
I think it's good to go in "as is". The known issues are understood and documented, all other updated will be made via separate PRs.

**Comment by mrakitin** [comment]
@ambarb, do you have any concerns regarding this update? It does not affect any code, just wanted to bring it to your attention.

**Comment by mrakitin** [comment]
This PR does not touch any startup files, self-merging.

**Pull request merged**
